package api_test

import (
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/PadenZach/maestro/internal/config"
	"github.com/PadenZach/maestro/internal/protocol"
	"github.com/PadenZach/maestro/internal/testserver"
)

const workflowRoot = "/v2/orgs/local/apps/fixture-app/workflows"

func record() map[string]any {
	return map[string]any{"WorkflowUUID": "wf-1", "Status": "SUCCESS", "WorkflowName": "job", "CreatedAt": "1720000000123", "UpdatedAt": "1720000000456", "Priority": "0", "WorkflowTimeoutMS": "0", "WorkflowDeadlineEpochMS": nil, "Attributes": "{\"secret\":true}", "WasForkedFrom": false}
}

func fixture(t *testing.T) (*httptest.Server, *testserver.Executor) {
	t.Helper()
	ts, h := testserver.New(t, config.Config{EnableAggregates: true})
	rows := make([]map[string]any, 30)
	for i := range rows {
		rows[i] = record()
		rows[i]["WorkflowUUID"] = fmt.Sprintf("wf-%d", i+1)
	}
	fe := testserver.Connect(t, ts, "fixture-app", "testkey", "exec-1", map[protocol.MessageType]testserver.Responder{
		protocol.MsgListWorkflows: func(req map[string]any) map[string]any {
			b := req["body"].(map[string]any)
			n := len(rows)
			if l, ok := b["limit"].(float64); ok && int(l) < n {
				n = int(l)
			}
			return map[string]any{"output": rows[:n]}
		},
		protocol.MsgGetWorkflow: func(req map[string]any) map[string]any {
			if req["workflow_id"] == "missing" {
				return map[string]any{"output": nil}
			}
			return map[string]any{"output": record()}
		},
		protocol.MsgListSteps: func(req map[string]any) map[string]any {
			return map[string]any{"output": []any{map[string]any{"function_id": 0, "function_name": "step-one", "started_at_epoch_ms": "1720000000123", "completed_at_epoch_ms": nil, "output": nil, "error": nil, "child_workflow_id": nil}}}
		},
	})
	testserver.Wait(t, func() bool { return len(h.Executors()) == 1 })
	return ts, fe
}

// Check actual HTTP responses against the documentation generated by the server.
func assertLocalV2Schema(t *testing.T, schema string, value map[string]any) {
	t.Helper()
	b := testserver.OpenAPI(t)
	var spec struct {
		Components struct {
			Schemas map[string]struct {
				Required   []string `json:"required"`
				Properties map[string]struct {
					Type   json.RawMessage `json:"type"`
					Format string          `json:"format"`
				} `json:"properties"`
			} `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(b, &spec); err != nil {
		t.Fatal(err)
	}
	s := spec.Components.Schemas[schema]
	if len(s.Required) == 0 {
		t.Fatalf("schema %s absent", schema)
	}
	for _, field := range s.Required {
		if _, ok := value[field]; !ok {
			t.Errorf("%s missing %s", schema, field)
		}
	}
	for key, v := range value {
		p, ok := s.Properties[key]
		if !ok {
			t.Errorf("%s unknown %s", schema, key)
			continue
		}
		var typ any
		_ = json.Unmarshal(p.Type, &typ)
		allowed := []string{}
		switch x := typ.(type) {
		case string:
			allowed = append(allowed, x)
		case []any:
			for _, i := range x {
				allowed = append(allowed, i.(string))
			}
		}
		actual := "string"
		switch v.(type) {
		case nil:
			actual = "null"
		case bool:
			actual = "boolean"
		case float64:
			actual = "integer"
		case map[string]any:
			actual = "object"
		}
		valid := false
		for _, a := range allowed {
			if a == actual || a == "number" && actual == "integer" {
				valid = true
			}
		}
		if !valid {
			t.Errorf("%s.%s: expected %v got %v", schema, key, allowed, v)
		}
		if p.Format == "date-time" && v != nil {
			if _, err := time.Parse(time.RFC3339Nano, v.(string)); err != nil {
				t.Errorf("%s.%s: %v", schema, key, err)
			}
		}
	}
}

func TestAPIWorkflowSchemaAndWire(t *testing.T) {
	ts, fe := fixture(t)
	code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+"/search", "POST", `{"limit":2,"offset":0,"sortDesc":false,"queuesOnly":false,"status":["SUCCESS"],"startTime":"2024-07-03T00:00:00Z"}`)
	if code != 200 || !strings.HasPrefix(ct, "application/json") {
		t.Fatalf("search: %d %s %s", code, ct, raw)
	}
	var list []map[string]any
	if err := json.Unmarshal([]byte(raw), &list); err != nil || len(list) != 2 {
		t.Fatalf("search rows: %s %v", raw, err)
	}
	if list[0]["workflowId"] != "wf-1" || list[1]["workflowId"] != "wf-2" {
		t.Fatalf("ids %v", list)
	}
	assertLocalV2Schema(t, "Workflow", list[0])
	if list[0]["createdAt"] != "2024-07-03T09:46:40.123Z" || list[0]["updatedAt"] != "2024-07-03T09:46:40.456Z" {
		t.Fatalf("createdAt: %v", list[0])
	}
	b := fe.Body(t, protocol.MsgListWorkflows)
	for k, v := range map[string]any{"limit": float64(2), "offset": float64(0), "sort_desc": false, "queues_only": false, "start_time": "2024-07-03T00:00:00Z"} {
		if b[k] != v {
			t.Errorf("wire %s = %v; want %v", k, b[k], v)
		}
	}
	code, _, raw = testserver.Request(t, ts.URL+workflowRoot+"/search", "POST", `{"workflowIds":["wf-1"],"user":["alice"],"status":["SUCCESS"],"workflowName":["job"],"appVersion":["v1"],"queueName":["q"],"endTime":"2024-07-04T00:00:00Z","sortDesc":true,"queuesOnly":true,"limit":0}`)
	if code != 200 || strings.TrimSpace(raw) != "[]" {
		t.Fatalf("all-filter/explicit zero: %d %s", code, raw)
	}
	wire := fe.Body(t, protocol.MsgListWorkflows)
	for httpField, wireField := range map[string]string{"workflowIds": "workflow_uuids", "user": "authenticated_user", "status": "status", "workflowName": "workflow_name", "appVersion": "application_version", "queueName": "queue_name"} {
		v, ok := wire[wireField].([]any)
		if !ok || len(v) != 1 {
			t.Fatalf("%s -> %s: %v", httpField, wireField, wire)
		}
	}
	if wire["end_time"] != "2024-07-04T00:00:00Z" || wire["sort_desc"] != true || wire["queues_only"] != true || wire["limit"] != float64(0) {
		t.Fatalf("filtered wire: %v", wire)
	}
	code, _, raw = testserver.Request(t, ts.URL+workflowRoot+"/search", "POST", `{"status":null}`)
	if code != 200 {
		t.Fatalf("nullable array: %d %s", code, raw)
	}
	if _, ok := fe.Body(t, protocol.MsgListWorkflows)["status"]; ok {
		t.Fatal("null status applied as filter")
	}
	code, _, raw = testserver.Request(t, ts.URL+workflowRoot+"/search", "POST", `{}`)
	if code != 200 {
		t.Fatalf("no limit: %d %s", code, raw)
	}
	if err := json.Unmarshal([]byte(raw), &list); err != nil || len(list) != 30 || list[29]["workflowId"] != "wf-30" {
		t.Fatalf("omitted limit >25: %s %v", raw, err)
	}
	if _, ok := fe.Body(t, protocol.MsgListWorkflows)["limit"]; ok {
		t.Fatal("hidden limit")
	}
	code, _, raw = testserver.Request(t, ts.URL+workflowRoot+"/wf-1", "GET", "")
	var wf map[string]any
	_ = json.Unmarshal([]byte(raw), &wf)
	if code != 200 {
		t.Fatalf("get: %d %s", code, raw)
	}
	assertLocalV2Schema(t, "Workflow", wf)
	if wf["priority"] != float64(0) || wf["timeoutMs"] != float64(0) || wf["deadline"] != nil || wf["attributes"] != "{\"secret\":true}" {
		t.Fatalf("wrong values: %v", wf)
	}
	code, _, raw = testserver.Request(t, ts.URL+workflowRoot+"/wf-1/steps?limit=0&offset=1", "GET", "")
	var steps []map[string]any
	_ = json.Unmarshal([]byte(raw), &steps)
	if code != 200 || len(steps) != 1 {
		t.Fatalf("steps: %d %s", code, raw)
	}
	assertLocalV2Schema(t, "Step", steps[0])
	if stepWire := fe.Body(t, protocol.MsgListSteps); stepWire["limit"] != float64(0) || stepWire["offset"] != float64(1) {
		t.Fatalf("step pagination wire: %v", stepWire)
	}
	if steps[0]["stepId"] != float64(0) || steps[0]["stepName"] != "step-one" || steps[0]["startedAt"] != "2024-07-03T09:46:40.123Z" || steps[0]["completedAt"] != nil {
		t.Fatalf("step: %v", steps[0])
	}
}

func TestAPIStrictErrors(t *testing.T) {
	ts, _ := fixture(t)
	// attributes, workflowIdPrefix, and explicit empty arrays are now supported by
	// the complete pinned WorkflowSearchBody implementation; the remaining cases
	// are still malformed or outside that schema.
	for _, body := range []string{`{"limit":-1}`, `{"limit":1.5}`, `{"limit":"2"}`, `{"limit":null}`, `{"status":42}`, `{"status":[null]}`, `{"startTime":"garbage"}`, `{"applicationName":["other"]}`, `{"unexpected":1}`, `{"limit":2,"limit":100}`, `{"limit":9223372036854775808}`, `{"sortDesc":null}`, `{"startTime":null}`} {
		code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+"/search", "POST", body)
		if code != 400 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "detail") {
			t.Errorf("body %s -> %d %s %s", body, code, ct, raw)
		}
	}
	for _, route := range []string{"/missing", "/missing/steps"} {
		code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+route, "GET", "")
		if code != 404 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "detail") {
			t.Errorf("%s: %d %s %s", route, code, ct, raw)
		}
	}
	code, _, _ := testserver.Request(t, ts.URL+"/v2/orgs/other/apps/fixture-app/workflows/wf-1", "GET", "")
	if code != 404 {
		t.Fatalf("other org: %d", code)
	}
	code, _, _ = testserver.Request(t, ts.URL+workflowRoot+"/search?bad=%zz", "POST", `{}`)
	if code != 400 {
		t.Fatalf("malformed search query ignored: %d", code)
	}
	code, _, _ = testserver.Request(t, ts.URL+workflowRoot+"/wf-1/steps?limit=2&bad=%zz", "GET", "")
	if code != 400 {
		t.Fatalf("malformed steps query ignored: %d", code)
	}
	code, _, _ = testserver.Request(t, ts.URL+workflowRoot+"/wf-1/steps?limit=bad", "GET", "")
	if code != 400 {
		t.Fatalf("bad steps query: %d", code)
	}
}

// The HTTP schema requires these fields: required executor collections and scalars must not be fabricated by
// Go's JSON zero values. Empty arrays and explicit false/zero remain valid.
func TestAPINullExecutorCollections(t *testing.T) {
	for _, tc := range []struct {
		name, route, method, body string
		command                   protocol.MessageType
	}{
		{"search-null", "/search", "POST", `{}`, protocol.MsgListWorkflows},
		{"steps-null", "/wf-1/steps", "GET", "", protocol.MsgListSteps},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ts, h := testserver.New(t, config.Config{EnableAggregates: true})
			testserver.Connect(t, ts, "fixture-app", "testkey", "exec-1", map[protocol.MessageType]testserver.Responder{
				protocol.MsgGetWorkflow: func(map[string]any) map[string]any { return map[string]any{"output": record()} },
				tc.command:              func(map[string]any) map[string]any { return map[string]any{"output": nil} },
			})
			testserver.Wait(t, func() bool { return len(h.Executors()) == 1 })
			code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+tc.route, tc.method, tc.body)
			if code != 502 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "detail") {
				t.Fatalf("null executor %s output: %d %s %s", tc.command, code, ct, raw)
			}
		})
	}
}

func TestAPIExplicitEmptyExecutorCollections(t *testing.T) {
	ts, h := testserver.New(t, config.Config{EnableAggregates: true})
	testserver.Connect(t, ts, "fixture-app", "testkey", "exec-1", map[protocol.MessageType]testserver.Responder{
		protocol.MsgGetWorkflow:   func(map[string]any) map[string]any { return map[string]any{"output": record()} },
		protocol.MsgListWorkflows: func(map[string]any) map[string]any { return map[string]any{"output": []any{}} },
		protocol.MsgListSteps:     func(map[string]any) map[string]any { return map[string]any{"output": []any{}} },
	})
	testserver.Wait(t, func() bool { return len(h.Executors()) == 1 })
	for _, tc := range []struct{ route, method, body string }{{"/search", "POST", `{}`}, {"/wf-1/steps", "GET", ""}} {
		code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+tc.route, tc.method, tc.body)
		if code != 200 || !strings.HasPrefix(ct, "application/json") || strings.TrimSpace(raw) != "[]" {
			t.Fatalf("explicit empty %s: %d %s %s", tc.route, code, ct, raw)
		}
	}
}

func TestAPIMissingExecutorRequiredScalars(t *testing.T) {
	for _, tc := range []struct {
		name, field, route string
		value              any
		missing            bool
	}{
		{"missing-step-id", "function_id", "/wf-1/steps", nil, true},
		{"null-step-id", "function_id", "/wf-1/steps", nil, false},
		{"missing-was-forked", "WasForkedFrom", "/wf-1", nil, true},
		{"null-was-forked", "WasForkedFrom", "/wf-1", nil, false},
		{"list-missing-was-forked", "WasForkedFrom", "/search", nil, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ts, h := testserver.New(t, config.Config{EnableAggregates: true})
			record := record()
			step := map[string]any{"function_id": 0, "function_name": "step-one"}
			if tc.route == "/wf-1/steps" {
				if tc.missing {
					delete(step, tc.field)
				} else {
					step[tc.field] = tc.value
				}
			} else if tc.missing {
				delete(record, tc.field)
			} else {
				record[tc.field] = tc.value
			}
			testserver.Connect(t, ts, "fixture-app", "testkey", "exec-1", map[protocol.MessageType]testserver.Responder{
				protocol.MsgGetWorkflow:   func(map[string]any) map[string]any { return map[string]any{"output": record} },
				protocol.MsgListWorkflows: func(map[string]any) map[string]any { return map[string]any{"output": []any{record}} },
				protocol.MsgListSteps:     func(map[string]any) map[string]any { return map[string]any{"output": []any{step}} },
			})
			testserver.Wait(t, func() bool { return len(h.Executors()) == 1 })
			method, body := "GET", ""
			if tc.route == "/search" {
				method, body = "POST", `{}`
			}
			code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+tc.route, method, body)
			if code != 502 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "detail") {
				t.Fatalf("%s source %s: %d %s %s", tc.name, tc.field, code, ct, raw)
			}
		})
	}
}

func TestAPIPresenceChecksDoNotChangeLegacyJSON(t *testing.T) {
	ts, h := testserver.New(t, config.Config{EnableAggregates: true})
	record := record()
	delete(record, "WasForkedFrom")
	testserver.Connect(t, ts, "fixture-app", "testkey", "exec-1", map[protocol.MessageType]testserver.Responder{
		protocol.MsgGetWorkflow: func(map[string]any) map[string]any { return map[string]any{"output": record} },
		protocol.MsgListSteps: func(map[string]any) map[string]any {
			return map[string]any{"output": []any{map[string]any{"function_name": "step-one"}}}
		},
	})
	testserver.Wait(t, func() bool { return len(h.Executors()) == 1 })
	code, _, raw := testserver.Request(t, ts.URL+"/api/fixture-app/workflows/wf-1", "GET", "")
	var workflow map[string]any
	if code != 200 || json.Unmarshal([]byte(raw), &workflow) != nil || workflow["WasForkedFrom"] != false {
		t.Fatalf("legacy workflow JSON changed: %d %s", code, raw)
	}
	code, _, raw = testserver.Request(t, ts.URL+"/api/fixture-app/workflows/wf-1/steps", "GET", "")
	var steps []map[string]any
	if code != 200 || json.Unmarshal([]byte(raw), &steps) != nil || len(steps) != 1 || steps[0]["function_id"] != float64(0) {
		t.Fatalf("legacy steps JSON changed: %d %s", code, raw)
	}
}

func TestAPIInvalidStepID(t *testing.T) {
	ts, h := testserver.New(t, config.Config{EnableAggregates: true})
	testserver.Connect(t, ts, "fixture-app", "testkey", "exec-1", map[protocol.MessageType]testserver.Responder{
		protocol.MsgGetWorkflow: func(map[string]any) map[string]any { return map[string]any{"output": record()} },
		protocol.MsgListSteps: func(map[string]any) map[string]any {
			return map[string]any{"output": []any{map[string]any{"function_id": 2147483648, "function_name": "overflow"}}}
		},
	})
	testserver.Wait(t, func() bool { return len(h.Executors()) == 1 })
	code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+"/wf-1/steps", "GET", "")
	if code != 502 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "stepId") {
		t.Fatalf("overflow step: %d %s %s", code, ct, raw)
	}
}

func TestAPIInvalidExecutorValues(t *testing.T) {
	for _, tc := range []struct {
		name  string
		field string
		value any
	}{
		{"bad-created", "CreatedAt", "not-an-epoch"}, {"overflow-priority", "Priority", "2147483648"},
		{"bad-timeout", "WorkflowTimeoutMS", "not-a-number"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ts, h := testserver.New(t, config.Config{EnableAggregates: true})
			record := record()
			record[tc.field] = tc.value
			testserver.Connect(t, ts, "fixture-app", "testkey", "exec-1", map[protocol.MessageType]testserver.Responder{
				protocol.MsgGetWorkflow: func(map[string]any) map[string]any { return map[string]any{"output": record} },
			})
			testserver.Wait(t, func() bool { return len(h.Executors()) == 1 })
			code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+"/wf-1", "GET", "")
			if code != 502 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "detail") {
				t.Fatalf("invalid %s: %d %s %s", tc.field, code, ct, raw)
			}
		})
	}
}

func TestAPIPrivacyRefusalIsNotRetried(t *testing.T) {
	ts, h := testserver.New(t, config.Config{EnableAggregates: true})
	var attempts atomic.Int32
	refusal := map[protocol.MessageType]testserver.Responder{protocol.MsgGetWorkflow: func(map[string]any) map[string]any {
		attempts.Add(1)
		return map[string]any{"error_message": "metadata-only refusal"}
	}}
	testserver.Connect(t, ts, "fixture-app", "testkey", "one", refusal)
	testserver.Connect(t, ts, "fixture-app", "testkey", "two", refusal)
	testserver.Wait(t, func() bool { return len(h.Executors()) == 2 })
	code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+"/wf-1", "GET", "")
	if code != 502 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "metadata-only refusal") || attempts.Load() != 1 {
		t.Fatalf("refusal bypass: %d %s %s attempts=%d", code, ct, raw, attempts.Load())
	}
}

func TestAPIUnavailable(t *testing.T) {
	ts, _ := testserver.New(t, config.Config{EnableAggregates: true})
	code, ct, raw := testserver.Request(t, ts.URL+workflowRoot+"/wf-1", "GET", "")
	if code != 503 || !strings.HasPrefix(ct, "application/problem+json") || !strings.Contains(raw, "detail") {
		t.Fatalf("unavailable: %d %s %s", code, ct, raw)
	}
}
